In [1]:
# NUMPY + PANDAS — THE FOUNDATION OF DATA SCIENCE

In [2]:
# NumPy (Numerical Python)
# Why Use NumPy?
 # Faster than Python lists
 # Useful for mathematical operations
 # Basis for all ML/AI libraries (e.g., TensorFlow, PyTorch)



In [5]:
# Import and Array Creation

import numpy as np

# Create 1D array
a = np.array([1, 2, 3, 4])
print(a)


# Create 2D array
b = np.array([[1, 2], [3, 4]])
print(b)



[1 2 3 4]
[[1 2]
 [3 4]]


In [6]:
# Array Operations

# Element-wise operations
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print(x + y)
print(x * y)
print(x / y)


[11 22 33]
[10 40 90]
[10. 10. 10.]


In [9]:
# NumPy Functions

print("Mean of Array x is: ", np.mean(x))        # Mean
print("Max element of Array x is: ",np.max(x))         # Max
print("Min element of Array x is: ",np.min(x))         # Min
print("Standard deviation of Array x is: ",np.std(x))         # Standard Deviation


Mean of Array x is:  20.0
Max element of Array x is:  30
Min element of Array x is:  10
Standard deviation of Array x is:  8.16496580927726


In [15]:
# Array Indexing and Slicing

arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])   # Output: [20 30 40]
print(arr[0:len(arr)]) 

[20 30 40]
[10 20 30 40 50]


In [16]:
# Pandas (Data Analysis Library)
# Why Use Pandas?
 # Easier to work with tables of data (like Excel/CSV)
 # Lets you load, filter, sort, group, analyze easily

